flask_login.py, test_login.py
=> Return HTTP401 for non fresh login

flask_login.py
Small grammatical change, their is used to show possession.
=> Changed there to their

docs/index.rst
=> Replace "MD5" with "secure hash" following 0.3.0

README.md, docs/index.rst, flask_login/__init__.py, flask_login/_compat.py, flask_login/config.py, flask_login/login_manager.py, flask_login/mixins.py, flask_login/signals.py, flask_login/utils.py, test_login.py
#286 without whitespace changes
=> Change all flask.ext.login to flask_login

flask_login/login_manager.py, test_login.py
=> better exception message for invalid cookie duration config

docs/index.rst
=> improve description of user class properties

docs/conf.py, docs/index.rst, flask_login/utils.py
Subject says it all I think and what it doesn't say the source does.
=> Fix doc build warnings and typos.

docs/index.rst
=> describe what remember me means

.travis.yml, README.md, dev-requirements.txt, requirements.txt
=> add coverage badge to readme

flask_login/__init__.py
Fixes #341 with a `flask_login.__version__`.
=> expose public __version__ module attribute

flask_login/login_manager.py, flask_login/utils.py
Please see discussion in #314.
=> Configurable generator of session _id

ISSUE_TEMPLATE.md
To hopefully help reduce the number of [non-issue questions](https://github.com/maxcountryman/flask-login/issues?q=is%3Aissue+stackoverflow+is%3Aclosed).
=> link to stackoverflow from issue template

README.md
'pw' variable to 'password'.
Basic HTML semantics.
=> Made variables more verbose for new users.

flask_login/login_manager.py
Though this is not that significant, but I think this is necessary for 2 reasons: 1. it's hard to find clear answer for both why and how to correct this, especially for newbie; 2. this is my first pull request for a popular and great project, it matters! ;)
=> Add docstring for the user_loader callback.

setup.py, tox.ini
=> Add py35,py36,pypy,pypy3 to tox and distutils categories

flask_login/login_manager.py, test_login.py
=> Accept int for REMEMBER_COOKIE_DURATION

docs/index.rst, flask_login/utils.py
* `REMEMBER_COOKIE_DURATION` now accepts integer number of seconds.
* `FORCE_HOST_FOR_REDIRECTS` new config option
=> update docs with new config options

flask_login/login_manager.py
Before:
> Refer to LoginManager. Refer tohttps://flask-login.readthedocs.io/en/latest/#how-it-works for more info.
After:
> Refer to LoginManager. Refer to https://flask-login.readthedocs.io/en/latest/#how-it-works for more info.
=> Add a missing space

MANIFEST.in
For the same reason as https://github.com/maxcountryman/flask-uploads/issues/2 :)
=> Include doc and tests in source distributions

MANIFEST.in
@alanhamlett sorry about the typo in https://github.com/maxcountryman/flask-login/pull/393
=> Fix docs in MANIFEST.in

docs/index.rst
Addresses #391 
Includes a link to the Flask sessions quickstart.
=> Add explanation of dependency on Flask secret key

dev-requirements.txt, test_login.py
[unittest.mock](https://docs.python.org/3.5/library/unittest.mock.html) is in standard library
=> Make mock package optional

docs/index.rst
Hi, it seems #426  PR is submitted but it doesn't include doc change so I'd like to add it. Documentation change for the PR below.
PR: https://github.com/maxcountryman/flask-login/pull/454
Fixes: #426
=> Change Documentation of HttpOnly flag from False to True

flask_login/config.py, flask_login/login_manager.py
=> Add REMEMBER_COOKIE_SAMESITE config

flask_login/login_manager.py
=> Only flash "needs_refresh_message" if value is set

flask_login/login_manager.py
=> Add accessors for request_loader and user_loader callback functions

README.md
=> remove incorrect example usage

flask_login/config.py
Resubmitting #454, as you seem to have missed all my other comments. Fixes #426.
I think you clicked the wrong button, or weren't paying enough attention, and closed the PR instead of merging it.
The followup PR that updates the documentation was merged, but the code change was not. So, currently, the documentation says this change has been made, but in fact it is still the old behaviour.
=> Resubmit #454

test_login.py
=> Import ABC from collections.abc

test_login.py
=> Fix deprecation warning: assertEqual(s)

docs/index.rst
=> Added little example of how use unauthorized_handler.

README.md, docs/index.rst, flask_login/config.py
When you [compare](https://github.com/maxcountryman/flask-login/compare/master) the `master` branch with the new `main` branch, the following three commits were somehow lost and are not in the `main` branch history. This PR restores the commits. I don't foresee an issue here since they've already been merged once before.
=> Restore commits lost on master branch

.gitignore, CHANGES, setup.py
- Updates `CHANGES` with all unreleased changes (so far)
- Use `README.md` for the long description instead of the docstring
- Remove broken `sys.argv[-1] '== 'test'` condition
=> Tweak setup.py + update CHANGES

dev-requirements.txt, flask_login/utils.py, test_login.py
Using current_app.ensure_sync as proposed here https://github.com/maxcountryman/flask-login/issues/589
=> use current_app.ensure_sync for asyncio compatibility

.github/workflows/tests.yaml, CHANGES, flask_login/utils.py, setup.py, test_login.py, tox.ini
Drop Python versions that have reached end of life.
=> python>=3.7 supported, drop 3.5 and 3.6

docs/index.rst
In ```{% if current_user.is_authenticated() %}``` the ```()``` should be omitted.
=> Fix template example in documentation

src/flask_login/utils.py
Fixes #657 and https://github.com/maxcountryman/flask-login/discussions/658.
=> Only preserve subdomain or host view args in login redirect

src/flask_login/utils.py
=> Fix for #662 - Better Flask 1.x detection

CHANGES.md, requirements/dev.txt, requirements/tests.in, requirements/tests.txt, src/flask_login/__about__.py, src/flask_login/__init__.py, tests/test_login.py
=> deprecate __about__ and __version__

CHANGES.md, src/flask_login/utils.py, tests/test_login.py
=> remove use of `X-Forwarded-For` header

docs/index.rst
=> Remove duplicate function in code example

CHANGES.md, src/flask_login/utils.py, tests/test_login.py
=> Remove LOGIN_DISABLED config
