flask_login.py, test_login.py
Fix for https://github.com/maxcountryman/flask-login/issues/62! A helpful error message is shown when a user loader callback has not been set. This prevents new flask-login users having to go through stackoverflow to decipher the `TypeError: 'NoneType'
object is not callable`
Implementation:
An explicit exception with a helpful error message is raised on
LoginManager.reload_user(), when the LoginManager.user_callback
has not been set.
Previously, the generic python exception (TypeError: 'NoneType'
object is not callable) gave no indication as to what the problem
might be.
=> Explicit error message when a user loader callback has not been set

flask_login.py, test_login.py
This fixes a wrong behavior in the strong protection. Now the
session protection is only tested if a session exists and
nothing is added to the session during the process.
Only one test is impacted and has been updated.
=> Fix session creation for every user

flask_login.py, test_login.py
The code that calculates a user's identifier uses the remote address or
the contents of the X-Forwarded-For header doesn't account for the fact
that the X-Forwarded-For header can contain a comma separated list of
remote addresses, which is the case for scenarios in which 2+ proxy
servers are involved in the request forwarding. This caveat causes
Flask-Login to unexpectedly log users out when the combination of proxy
servers that routed a previous request change.
See http://tools.ietf.org/html/rfc7239 for more information about
X-Forwarded-For standard.
=> Fix handling of X-Forwarded-For header

docs/index.rst
By moving the "Your User Class" description to before the example that uses it, the reader is aware that they need a user class before getting to the example. I got a bit confused as to what user was meant to be until I re-read and read further on down
=> Put User class description before example

docs/index.rst
That's how accusative and "that one" work in Esperanto. You could also replace "that one" (tiun) with "this one" (ĉi-tiun or tiun ĉi), but in my opinion that's much uglier.
=> Improved grammar

flask_login.py, test_login.py
As of 2fc6a7e06b560233eadb44f8eba74e2a1bce88be, the `TESTING` config variable is no longer used, but is still referenced by the docs for login_required, at least.
=> Docs still name `TESTING`

flask_login.py, test_login.py
This patch addresses the recurrent problem of Flask-Login clearing session data stored by the application or other extensions. I have also expanded one of the unit tests to ensure unrelated data in the session is not deleted.
=> do not clear entire session, just Flask-Login variables (fixes #231)

flask_login.py, test_login.py
Exempt OPTIONS calls from login
W3 guidelines dictate that CORS preflight requests do not send user credentials, therefore no login checks should be performed on these requests.
http://www.w3.org/TR/cors/#cross-origin-request-with-preflight-0
Closes #243
=> Exempt OPTIONS calls from login

docs/index.rst
Added descriptions for the following configuration options in the "Cookie Settings" section of the documentation:
REMEMBER_COOKIE_SECURE
REMEMBER_COOKIE_HTTPONLY
=> Add SECURE and HTTPONLY to cookie settings documentation

CONTRIBUTING.md, README.md
As per [their blog post of the 27th April](https://blog.readthedocs.com/securing-subdomains/) ‘Securing subdomains’:
> Starting today, Read the Docs will start hosting projects from subdomains on the domain readthedocs.io, instead of on readthedocs.org. This change addresses some security concerns around site cookies while hosting user generated data on the same domain as our dashboard.
Test Plan: Manually visited all the links I’ve modified.
=> Convert readthedocs links for their .org -> .io migration for hosted projects

Makefile, flask_login/__init__.py, flask_login/login_manager.py, flask_login/mixins.py
Also runs the `clean` build step when running `make check` to clean up `*.pyc` files so you can run tests multiple times without having to delete compiled modules manually.
=> rename mixin to be plural

docs/index.rst
Changed some leftover instances of "methods" to say "properties" instead.
=> Update doc to reflect User properties (instead of methods)

docs/_themes/flask_small/layout.html
This prevents the mixed content warning when the docs are hosted on an HTTPS site (like [Read The Docs](https://flask-login.readthedocs.io/en/latest/)).
Also, use an HTTPS link for the GitHub project.
=> Use HTTPS link for GitHub ribbon image

.travis.yml, install_requirements.py
And removed the call to pip from .travis.yml since that is handled by install_requirements.py. Pypi uses a CDN now so mirrors are no longer used and the use-mirrors option is no longer available for pip.
=> Remove mirror use for pip since that is no longer a pip option. 

setup.py
This will update the links on pypi on the next release.
=> docs are hosted on readthedocs

dev-py2-requirements.txt, dev-py3k-requirements.txt, dev-requirements.txt, flask_login/login_manager.py, install_requirements.py, requirements.txt, test_login.py, tox.ini
* upgrade python requirements
* remove duplicate requirements by recursively specifying requirements
files
* use semantic_version for more robust test skipping
=> upgrade python requirements to latest versions

flask_login/login_manager.py
The index.rst mentions this is deprecated, but for clarity also adding it to the function documentation.
=> Repeat `header_loader` deprecation in API doc

run-tests.sh
Under distributions like Debian the Python 3 version of `nosetests` is installed as `nosetests3`. This change allows the hardcoded name `nostetests` to be overridden with an environment variable `NOSETESTS` when calling the test runner script to accommodate running the tests in this case.
=> Allow nosetests executable path to be specified

docs/index.rst, flask_login/config.py, flask_login/login_manager.py, flask_login/utils.py, test_login.py
I'm a fan of "pretty" urls and would prefer that it just says www.example.com/login and not a long parameter string. This was already requested in issue #123.
I added a config variable `USE_SESSION_FOR_NEXT` which defaults to false, but when set to true engages the feature.
I had to do some minor refactoring of utils to avoid duplication.
I added a test and updated the docs.
=> Add option to store 'next' in session rather than the url.

flask_login/login_manager.py, test_login.py
My last PR #330 had an error on my part. I didn't realize that fresh logins were handled separately. I updated that function to use the session as well and added a test for this.
Sorry about that.
I did a ctrl-F audit of `login_manager.py` and it looks I have caught all instances of `login_url` so I think we are good now.
=> Fixed omission in USE_SESSION_FOR_NEXT

flask_login/login_manager.py
This is a cosmetic change that imports `utils.login_url` as `make_login_url` so we can have variables named `login_url` in `LoginManager`.
This was to remove confusion around two urls being passed to `make_login_url`, but passing `next_url` as a named param could be enough to remove confusion. Let me know which way everyone thinks is best.
=> improve readability of login_url by renaming it as make_login_url

docs/index.rst
Adds a code example for disabling the [Flask Session cookie](http://flask.pocoo.org/docs/0.12/quickstart/#sessions) for API requests, based on the user loader callback that was used to authenticate the current user.
Fixes #163, #240, #159.
Related to #98, #24, #179, #181, #196, #24, #109, #120.
=> Example of disabling Flask Session cookie for API requests

docs/index.rst, flask_login/login_manager.py, flask_login/utils.py, test_login.py
Add the optional parameter 'duration' to the method login_user to define the duration of the 'remember me' cookie. The parameter receives a timedelta object, which is the same object used for the 'COOKIE_DURATION' configuration. 
It implements #105
=> Add parameter 'duration' to login_user

docs/index.rst, flask_login/login_manager.py, test_login.py
Similar to Flask's `SESSION_REFRESH_EACH_REQUEST`, but for the remember
me cookie.
Off by default, can be turned on by setting the config parameter.
`REMEMBER_COOKIE_REFRESH_EACH_REQUEST` to `True`.
=> Add support for refreshing the remember me cookie on every request.

flask_login/utils.py, test_login.py
Flask-Login's default unauthorized handler uses `Flask.redirect` to redirect to the login page. When a request is made to a route decorated with `@login_required`, then `Flask.redirect` correctly uses the `Host` or `X-Forwarded-For` as the host part of the redirect url.
This is fine, except in SSO applications or pen-tests. For those who don't mind breaking proxies, this PR adds a new config `FORCE_HOST_FOR_REDIRECTS` that always overwrites the host in `flask_login.utils.login_url` which is used when redirecting to the login url.
=> Ability to force host used when redirecting

flask_login/login_manager.py, flask_login/utils.py, test_login.py
This does a few things to simplify user loading:
* Only set user on current request context once in `LoginManager._load_user`
* Rename `LoginManager.reload_user` to `LoginManager._update_request_context_with_user`
* Stop loading user from session in `LoginManager._update_request_context_with_user`
* Load user from session in `LoginManager._load_user`
* Raise exception when loading user when both `user_loader` and `request_loader` undefined
=> Simplify user loading

docs/conf.py
Otherwise I get
```
copying static files... WARNING: html_static_path entry '/var/tmp/portage/dev-python/flask-login-0.4.1/work/flask-login-0.4.1/docs/_static' does not exist                                                                                                                                 
```
=> Remove unused html_static_path from docs to avoid warning

docs/index.rst
Prompted by #395, this improves the Alternative Token docs section.
=> improve alternative token docs section

flask_login/login_manager.py, test_login.py
Addresses #401.
It may make sense to refactor the "login session" code so that this doesn't need to be a repeated issue throughout the code.
=> Set session ID when setting next

flask_login/login_manager.py, flask_login/utils.py, test_login.py
Fixes #409.
Left `LoginManager._login_disabled` available as a legacy property, but it now only works within an app context.
=> Read login disabled from app config instead of storing on login manager

.travis.yml
Coveralls removed support for Python 2.6, so only run coveralls on newer versions of Python.
=> Disable coveralls for Travis when env is Python 2.6

flask_login/utils.py, test_login.py
My organization uses blueprints to separate logical apps in our Flask app, creating blueprint-specific secret keys for cookie encoding.
We have been using some hackery to get `flask_login` working by overriding `utils._secret_key()`.  I was hoping that we could add support for an explicit key for cookie encoding here, as it would make our code much simpler and it seems like something that may be useful to others as well.
Please let me know if you have any questions or concerns.  Thanks!
=> Add support for an explicit key when calling encode_cookie() and decode_cookie()

CHANGES, docs/conf.py, docs/index.rst, flask_login/__init__.py, flask_login/test_client.py, test_login.py
Having a custom test client makes it easier to write automated tests using Flask-Login.
=> Custom test client

flask_login/test_client.py
I forgot that a user class doesn't necessarily need to have an `id` property -- it only needs to have a `get_id()` method.
=> test client: refer to get_id()

CHANGES, flask_login/__about__.py
Fixes #425. We should probably also include changelog entries for #378, #403, #404, #410, and #414.
Once this is merged, the following tasks need to happen:
=> version 1.0.0

CHANGES, flask_login/config.py, flask_login/login_manager.py, flask_login/test_client.py, flask_login/utils.py, test_login.py
To prevent accidental usage in app code. Fixes #465.
=> Prefix internal session keys with underscore

flask_login/utils.py
The current implementation will throw the following error when using dynamic subdomain or host matching in Flask:
> werkzeug.routing.BuildError: Could not build url for endpoint 'login'. Did you forget to specify values ['tenant_name']?
This change will allow for the following:
```
login_manager.login_view = 'login'
@app.route('/', subdomain='<tenant_name>')
@login_required
def dashboard(tenant_name):
...
@app.route('/login', methods=['GET', 'POST'], subdomain='<tenant_name>')
def login(tenant_name):
...
```
=> Modify expand_login_view to allow for subdomain and host matching for login_view

test_login.py
There is a small typo in test_login.py.
Should read `permanent` rather than `permament`.
=> docs: Fix simple typo, permament -> permanent

dev-requirements.txt, test_login.py
I'll get actual pinning for the test env next, wanted to get the tests updated to be compatible first.
=> get tests working with latest flask/werkzeug

README.md, docs/index.rst, flask_login/config.py
When I want to check if the user is authenticated, I get a UnicodeEncodeError error because you are using latin-1 encoding on line 387 only I changed the encoding to utf-8 the error immediately disappeared.
It can appear in different places, for example when the user is not logged in or when he tries to log in. Here are my code examples.
decorators.py
```py
def is_auth(f):
@wraps(f)
def decorate_func(*args, **kwargs):
if current_user.is_authenticated:
return redirect(url_for('.index'))
return f(*args, **kwargs)
return decorate_func
```
views.py
```py
@main.route('/login/', methods=['post', 'get'])
@is_auth
def login():
form = LoginForm()
if form.validate_on_submit():
user = find_data.find_user(email=form.email.data)
if user and user.check_password(form.password.data):
login_user(user, …
```
=> Problems with utils.py

CHANGES, flask_login/__init__.py
`__all__` should only contain strings with importable names. fixes #485
=> fix `from flask_login import *`

README.md
I wonder if this would be the more correct behaviour or not?
=> Set HTTP response code to 401 when unauthorized (in example)

docs/index.rst
This change fixes the docs which earlier pointed to the now deprecated `header_loader`, in the section describing the process for disabling session cookies for APIs. It now correctly refers to the `request` related imports / other settings to achieve this.
Relevant issue: #478
=> Document disabling of session cookie for `request_loader`

docs/index.rst
In the current documentation, there is no description about blueprint_login_views or how to set it through login_manager.
=> Add description for blueprint_login_views in docs

CHANGES, flask_login/mixins.py, test_login.py
Everyone usually overrides [UserMixin.is_authenticated](https://flask-login.readthedocs.io/en/latest/_modules/flask_login/mixins.html#UserMixin) to check `self.is_active`, so let's just make that the default implementation.
Fixes #486.
=> Better UserMixin.is_authenticated default implementation

CHANGES.md, src/flask_login/login_manager.py, tests/test_login.py
Only set _fresh to False if not already set. This prevents tripping session.modified, which forces a new session cookie to be sent with the response.
Only a minor annoyance, but after a useragent/ip change, if using basic session protection, every response will include a new session cookie if current_user is accessed.
edit: Or _id could be updated to prevent tripping session protection again until the next change.
closes #612
=> basic session protection: only set _fresh when needed

.github/workflows/lock.yaml
This workflow runs daily and locks any closed issues and PRs that have not had any activity in the last 14 days.
This has been very helpful in other projects to limit "drive by reporting" where users will resurrect closed issues with new comments rather than opening a new issue.
Recently, many stale issues were closed due to limited maintainer availability. If you come across an issue that was closed without discussion, and you still feel it is an issue, please open a new issue. Given the lack of maintainer availability, consider submitting a PR as well if the issue is important to you.
=> lock old threads

README.md, docs/index.rst
Re #656.
Addresses misunderstanding that more configuration than is explicitly mentioned in docs exists.
As some keys may collide with other flask modules, such misunderstanding has potential for unexpected behavior and therefore security issues. This will at least highlight that further config exists and that the responsibility falls on the user.
=> docs: Add note on where to find available configuration

docs/index.rst, tests/test_login.py
With the alternative implementation for the utility function `login_remembered()` in #654 merged, there are some inconsistencies in documentation and tests:
- The `remembered_login` option to the `FlaskLoginClient` was never merged and as such may be removed from the documentation.
- Tests for the 'remember me' flag are related to user login functionality and as such belong to the `LoginTestCase` rather than the `CustomTestClientTestCase`.
This patch resolves these inconsistencies.
=> Clean up docs and tests after merging `login_remembered()`

docs/index.rst, tests/test_login.py
The bundled test client `FlaskLoginClient` seems to make the assumption that session protection is disabled. When [instantiating the test client](https://github.com/maxcountryman/flask-login/blob/ecd3b59339175e575ba598eb5c5fd3330e0ff73b/src/flask_login/test_client.py#L16-L19=), the visitor's identifier generated for each incoming request (i.e. the `_id` session variable) is not stored. Requests made with this test client instance will therefore always fail the session protection check.
As a result:
- The `fresh_login` keyword parameter has no effect when session protection is enabled in `basic` mode, as it's always overridden to a non-fresh session.
- The `user` keyword parameter has no effect when session protection is enabled in `strong` mode, as it's always overridden to an anonymous …
=> Clarify usage of `FlaskLoginClient` test client

CHANGES.md, src/flask_login/login_manager.py, src/flask_login/utils.py
* Revert #462 and #663. Dynamic domain values should be managed with `app.url_value_preprocessor` and `app.url_defaults`, not by trying to re-parse the rule on every build.
fixes #686 
* Store the user on `g._login_user` instead of `_app_ctx_stack.top.user`.
fixes #690
=> compatibility with Werkzeug 2.2 and Flask 2.2

CHANGES.md, docs/index.rst, src/flask_login/__init__.py, src/flask_login/login_manager.py, src/flask_login/signals.py, tests/test_login.py
Ensure deprecation warnings are present for deprecated features that will be removed in the 0.7 feature release.
- Use `request_loader` instead of `header_loader`.
- Use `user_loaded_from_request` instead of `user_loaded_from_header`.
- Use `app.config["LOGIN_DISABLED"]` instead of `_login_disabled`.
- Use `init_app` instead of `setup_app`.
=> ensure deprecation warnings

CHANGES.md, docs/index.rst, src/flask_login/__init__.py, src/flask_login/config.py, src/flask_login/login_manager.py, src/flask_login/signals.py
To get ready for a new feature release as per [this comment](https://github.com/maxcountryman/flask-login/discussions/670#discussioncomment-2768626).
* `header_loader`
* `user_loaded_from_header`
* `setup_app`
* `_login_disabled`
=> remove previously deprecated code

CONTRIBUTING.md
There are small typos in:
- CONTRIBUTING.md
Fixes:
- Should read `occasionally` rather than `ocassionally`.
- Should read `guidelines` rather than `guidlines`.
Semi-automated pull request generated by
https://github.com/timgates42/meticulous/blob/master/docs/NOTE.md
=> docs: Fix a few typos

docs/index.rst
The `flask-login` docs point to a non-existent / deprecated snippet for the implementation of the `is_safe_url` function. There are a few points worth mentioning here:
* The link is broken 😢 
* The implementation referenced has a weakness / vulnerability (details below the fold)
*  The naming of `is_safe_url` isn't as descriptive as it could be on what the function is actually doing -- suggest following Django's lead here and moving to `url_has_allowed_host_and_scheme`
This PR updates the docs to point to a non-broken link. The implementation it points to is also more robust from a security standpoint.
---
The existing snippet `is_safe_url` implementation is:
```python
from urllib.parse import urlparse, urljoin
def is_safe_url(target):
ref_url = urlparse(request.host_url)
test_url = …
```
=> Update Docs to Reference a Non-Vulnerable alternative to `is_safe_url`

setup.py, tests/test_login.py
The cookie_jar property is deprecated in Werkzeug 2.3 and will be removed in Werkzeug 2.4.  The current LoginTestCase does not work with Werkzeug 2.3.  Revised the test case to work with Werkzeug 2.3 and above.
=> Revised the LoginTestCase to work with Werkzeug 2.3

src/flask_login/utils.py
=> fix: avoid DeprecationWarning 'werkzeug.urls.url_decode' is deprecated

.pre-commit-config.yaml, CHANGES.md, requirements/ci-release.txt, requirements/ci-tests.txt, requirements/dev.txt, requirements/docs.txt, requirements/style.txt, requirements/tests.txt, src/flask_login/__about__.py, src/flask_login/utils.py, tests/test_login.py
This branches off the 0.6.2 tag, and redoes the compatibility fixes. The previous fixes were merged into main, which already had some changes for 0.7, while 0.6.3 should only be about fixes. The fixes are also a bit different than the previous PRs.
The Werkzeug test client's cookie methods changed, and the tests now pass with both Werkzeug<2.3 and latest. 0.7 will drop this Werkzeug<2.3 compat later.
Werkzeug 3 no longer has an outdated copy of urllib, so we import directly from Python's built-in `urllib.parse` instead. The more modern `urlsplit` is used instead of `urlparse` as well.
This will not merge cleanly into main through GitHub, so I will merge it manually. That may be why the CI tests didn't run here, but they do pass locally. I will start the release process tomorrow.
=> Flask and Werkzeug 3 compat, release 0.6.3

CHANGES.md, src/flask_login/login_manager.py, tests/test_login.py
`datetime.utcnow`, which returns a naive datetime, is deprecated in favor of `datetime.now(timezone.utc)`, which returns an aware datetime with the UTC timezone. Werkzeug and Flask already updated to use aware datetimes in their headers and other values.
Already addressed many of the tests using `utcnow` in #813. This fixes the one use in the source, and the tests that referenced it.
fixes #758
=> use `datetime.now` with timezone instead of `utcnow`
